In [33]:
import pandas as pd

In [ ]:
df_2023 = pd.read_csv('../data/atp_matches_2023.csv')
df_2024 = pd.read_csv('../data/atp_matches_2024.csv')
df_2025 = pd.read_csv('../data/atp_matches_2025.csv')

df_2024.info()
# give the columns, non null count and data type of each column
# player_id como identificador dos jogadores

<class 'pandas.DataFrame'>
RangeIndex: 3076 entries, 0 to 3075
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          3076 non-null   str
 1   tourney_name        3076 non-null   str
 2   surface             3076 non-null   str
 3   draw_size           3076 non-null   int64
 4   tourney_level       3076 non-null   str
 5   tourney_date        3076 non-null   int64
 6   match_num           3076 non-null   int64
 7   winner_id           3076 non-null   int64
 8   winner_seed         1294 non-null   float64
 9   winner_entry        477 non-null    str
 10  winner_name         3076 non-null   str
 11  winner_hand         3076 non-null   str
 12  winner_ht           3057 non-null   float64
 13  winner_ioc          3076 non-null   str
 14  winner_age          3075 non-null   float64
 15  loser_id            3076 non-null   int64
 16  loser_seed          757 non-null    float64
 17  loser_entry         718 non-null    str
 18  loser_name          3076 non-null   str
 19  loser_hand          3076 non-null   str
 20  loser_ht            3026 non-null   float64
 21  loser_ioc           3076 non-null   str
 22  loser_age           3075 non-null   float64
 23  score               3076 non-null   str
 24  best_of             3076 non-null   int64
 25  round               3076 non-null   str
 26  minutes             2838 non-null   float64
 27  w_ace               3016 non-null   float64
 28  w_df                3016 non-null   float64
 29  w_svpt              3016 non-null   float64
 30  w_1stIn             3016 non-null   float64
 31  w_1stWon            3016 non-null   float64
 32  w_2ndWon            3016 non-null   float64
 33  w_SvGms             3015 non-null   float64
 34  w_bpSaved           3016 non-null   float64
 35  w_bpFaced           3016 non-null   float64
 36  l_ace               3016 non-null   float64
 37  l_df                3016 non-null   float64
 38  l_svpt              3016 non-null   float64
 39  l_1stIn             3016 non-null   float64
 40  l_1stWon            3016 non-null   float64
 41  l_2ndWon            3016 non-null   float64
 42  l_SvGms             3015 non-null   float64
 43  l_bpSaved           3016 non-null   float64
 44  l_bpFaced           3016 non-null   float64
 45  winner_rank         3059 non-null   float64
 46  winner_rank_points  3059 non-null   float64
 47  loser_rank          3036 non-null   float64
 48  loser_rank_points   3036 non-null   float64
dtypes: float64(29), int64(6), str(14)
memory usage: 1.2 MB

In [ ]:
# o isna().sum() devolve um objeto do tipo series. A partir daí consigo filtrar

series = df_2023.isna().sum()
series = series[series > 500]
print(series)

# winner_seed     1736
# winner_entry    2513
# loser_seed      2217
# loser_entry     2291

winner_seed     1736
winner_entry    2513
loser_seed      2217
loser_entry     2291
dtype: int64

In [34]:
# A maneira que consegui para ver todas as colunas. As colunas estavam a ser ocultas, por serem muitas

df_2024.head().T

#surface
#winner_id - uma vez que vou ter uma tabela de jogadores, isto é suficiente
#winner_hand
#winner_ht
#winner_rank
#loser_id - uma vez que vou ter uma tabela de jogadores, isto é suficiente
#loser_hand
#loser_rank
#score

,0,1,2,3,4
tourney_id,2024-0339,2024-0339,2024-0339,2024-0339,2024-0339
tourney_name,Brisbane,Brisbane,Brisbane,Brisbane,Brisbane
surface,Hard,Hard,Hard,Hard,Hard
draw_size,32,32,32,32,32
tourney_level,A,A,A,A,A
tourney_date,20240101,20240101,20240101,20240101,20240101
match_num,300,299,298,297,296
winner_id,105777,208029,105777,208029,126128
winner_seed,2.0,1.0,2.0,1.0,NaN
winner_entry,NaN,NaN,NaN,NaN,NaN
winner_name,Grigor Dimitrov,Holger Rune,Grigor Dimitrov,Holger Rune,Roman Safiullin
winner_hand,R,R,R,R,R
winner_ht,191.0,188.0,191.0,188.0,185.0
winner_ioc,BUL,DEN,BUL,DEN,RUS
winner_age,32.6,20.6,32.6,20.6,26.4
loser_id,208029,126128,111442,105902,208286
loser_seed,1.0,NaN,NaN,NaN,NaN
loser_entry,NaN,NaN,NaN,Q,NaN
loser_name,Holger Rune,Roman Safiullin,Jordan Thompson,James Duckworth,Matteo Arnaldi
loser_hand,R,R,R,R,R
loser_ht,188.0,185.0,183.0,183.0,185.0
loser_ioc,DEN,RUS,AUS,AUS,ITA
loser_age,20.6,26.4,29.7,31.9,22.8
score,7-6(5) 6-4,6-4 7-6(0),6-3 7-5,6-2 7-6(6),7-6(4) 6-2
best_of,3,3,3,3,3
round,F,SF,SF,QF,QF
minutes,136.0,97.0,109.0,105.0,120.0
w_ace,8.0,7.0,10.0,13.0,9.0
w_df,2.0,4.0,3.0,0.0,3.0
w_svpt,74.0,72.0,67.0,65.0,73.0
w_1stIn,52.0,48.0,45.0,36.0,43.0
w_1stWon,40.0,39.0,39.0,31.0,36.0
w_2ndWon,13.0,11.0,10.0,17.0,14.0
w_SvGms,11.0,11.0,11.0,10.0,10.0
w_bpSaved,3.0,1.0,6.0,1.0,2.0
w_bpFaced,3.0,2.0,6.0,1.0,3.0
l_ace,9.0,5.0,5.0,5.0,3.0
l_df,3.0,5.0,1.0,2.0,2.0
l_svpt,95.0,66.0,62.0,77.0,69.0
l_1stIn,58.0,35.0,39.0,51.0,37.0
l_1stWon,44.0,31.0,24.0,31.0,27.0
l_2ndWon,16.0,10.0,14.0,16.0,16.0
l_SvGms,11.0,11.0,10.0,10.0,10.0
l_bpSaved,8.0,5.0,5.0,3.0,5.0
l_bpFaced,9.0,7.0,7.0,5.0,8.0
winner_rank,14.0,8.0,14.0,8.0,39.0
winner_rank_points,2570.0,3660.0,2570.0,3660.0,1122.0
loser_rank,8.0,39.0,55.0,116.0,44.0
loser_rank_points,3660.0,1122.0,902.0,573.0,1021.0

In [58]:
df_all = pd.concat([df_2023, df_2024, df_2025]).sort_values(by=['tourney_date', 'match_num']).reset_index(drop=True)

df_all['UncompletedMatch'] = df_all['score'].str.contains('W/O') | df_all['score'].str.contains('RET')

In [ ]:
df_all = df_all[['tourney_id', 'tourney_name', 'tourney_date', 'tourney_level', 'match_num', 'surface', 'round', 'winner_id', 'winner_rank', 'loser_id', 'loser_rank', 'score', 'UncompletedMatch']]

df_all.head()

,surface,winner_id,winner_hand,winner_rank,loser_id,loser_hand,loser_rank,score
0,Hard,105777,R,14.0,208029,R,8.0,7-6(5) 6-4
1,Hard,208029,R,8.0,126128,R,39.0,6-4 7-6(0)
2,Hard,105777,R,14.0,111442,R,55.0,6-3 7-5
3,Hard,208029,R,8.0,105902,R,116.0,6-2 7-6(6)
4,Hard,126128,R,39.0,208286,R,44.0,7-6(4) 6-2